In [1]:
import pandas as pd

In [8]:
df=pd.read_csv('data/survey_results_public.csv',index_col='Respondent')

In [9]:
pd.set_option('display.max_columns',80)

In [10]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Appropriate in length,Easy

In [13]:
df['ConvertedComp'].median()

np.float64(57287.0)

In [15]:
df.median(numeric_only=True)

CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [16]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [18]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [20]:
df['SocialMedia'].value_counts(normalize=True)

SocialMedia
Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: proportion, dtype: float64

In [21]:
country_grp=df.groupby('Country')

In [22]:
country_grp.get_group('Nepal')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
508,I am a student who is learning to code,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Not employed, but looking for work",Nepal,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Academic researcher;Designer;Developer, full-s...",1,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;HTML/CSS;JavaScript,HTML/CSS;JavaScript;SQL;TypeScript,Firebase;MongoDB,Firebase;MongoDB;MySQL;PostgreSQL,Heroku;Windows,Android;Arduino;Docker;Heroku;Linux;Raspberry ...,Express;React.js,Express;React.js;Vue.js,Node.js,Node.js;React Native;TensorFlow,Visual Studio Code,Windows,"Development;Outside of work, for personal proj...",NaN,Useful for immutable record keeping outside of...,Yes,Yes,What?,Facebook,NaN,NaN,2018,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",A lot less welcome now than last year,Industry news about technologies you're intere...,NaN,Too long,Neither easy nor difficult
592,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Nepal,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Database administrator;Developer, back-end",4,20,3,Slightly dissatisfied,Very dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,Complete a take-home project;Interview with pe...,No,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,NPR,Nepalese rupee,NaN,Monthly,NaN,48.0,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Lack of s...,Less than once per month / Never,Office,Average,"Yes, because I was told to do so",2.0,NaN,NaN,NaN,C;C++;HTML/CSS;PHP;Python;SQL,HTML/CSS;Python;SQL,Elasticsearch;MongoDB;MySQL;PostgreSQL,Elasticsearch;Firebase;MongoDB;PostgreSQL;Redis,AWS;Linux;WordPress,Android;AWS;Linux,Django,Django;Laravel;React.js,NaN,Flutter;Hadoop;Node.js;TensorFlow,Sublime Text;Visual Studio Code,Linux-based,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,YouTube,In real life (in person),Username,2016,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are",Not sure,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Appropriate in length,Neither easy nor difficult
984,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Nepal,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Participated in a full-time developer training...,20 to 99 employees,Academic researcher;Data or business analyst;D...,6,14,2,Very satisfied,Very satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard)",No,Industry that I'd be working in;Specific depar...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,10000.0,Yearly,10000.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Inadequate access...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,C++;Go;Other(s):,Assembly;Go;Other(s):,MySQL;Other(s):,NaN,AWS;Linux;Slack;Other(s):,AWS;IBM Cloud or Watson;Linux;Slack;Other(s):,NaN,NaN,Other(s):,Other(s):,IntelliJ;Visual Studio Code,Linux-based,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,Yes,What?,LinkedIn,NaN,NaN,2014,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,25.0,Too long,Neither easy nor difficult
1355,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Nepal,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",100 to 499 employees,"Developer, back-end;Developer, front-end;Devel...",5,13,Less than 1 year,Slightly satisfied,Slightly satisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,NaN,No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NPR,Nepalese rupee,30000.0,Monthly,3168.0,40.0,There's no schedule or spec; I work on what se...,Not enough people for the workload;Toxic work ...,Less than once per month / Never,Home,Average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't","The CTO, CIO, or other management purchase new...",I have little or no influence,HTML/CSS;Java;JavaScript;SQL;TypeScript,Go;JavaScript;SQL;Swift;TypeScript,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;PostgreSQL,Android;Linux;Windows,Linux,Express;React.js,Express;React.js,Node.js,Node.js,Android Studio;IntelliJ;Visual Studio Code,Linux-based,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,Yes,YouTube,In real life (in person),Username,NaN,Daily or almost daily,Find answers to specific questions,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Too long,Easy
1783,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Nepal,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Academic researcher;Developer, back-end",2,12,1,Slightly satisfied,Slightly satisfied,Not at all confident,No,Yes,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,NPR,Nepalese rupee,16000.0,Monthly,1692.0,48.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,Average,No,NaN,"No, but I think we should",Not sure,I have some influence,Python,Python,PostgreSQL;SQLite,PostgreSQL,Docker;Linux;MacOS,Docker;Linux;MacOS,Other(s):,Other(s):,NaN,NaN,Atom;Vim,MacOS,Development,Not at all,NaN,Yes,Yes,Yes,Facebook,Online,Username,2014,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86618,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Nepal,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Developer, front-end",3,22,1,Very satisfied,Slightly dissatisfied,Not at all confident,No,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,1000.0,Monthly,12000.0,50.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have little or no influence,HTML/CSS;Java;JavaScript;Python;Ruby,Go;HTML/CSS;JavaScript;Python;TypeScript,Firebase;MongoDB,Firebase;MongoDB,Android;AWS;Docker;Heroku;MacOS;Raspberry Pi,AWS;Docker;Heroku;MacOS,Express;React.js,Express;React.js,Node.js;React Native,Node.js;React Native,Visual Studio Code;Xcode,MacOS,"Development;Production;Outside of work, for pe...",Not at all,Useful across many domains and could change ma...,No,Yes,Yes,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,Stack Overflow was slightly faster,31-60 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,27.0,Appropriate in length,Easy
86742,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Nepal,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, full-stack",3,16,2,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Financial perf...,"Something else changed (education, award, medi...",NPR,Nepalese rupee,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Distracting work environment;Time spent commut...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's part of our process",Not sure,I have some influence,PHP,PHP;Python,MySQL;Oracle;Redis;SQLite,MariaDB;MongoDB;MySQL;PostgreSQL;Redis;SQLite,AWS;Linux;Slack;WordPress,AWS;Docker;Google Cloud Platform;Linux;Raspber...,Django;Laravel,Django;Flask;Laravel;Vue.js,NaN,TensorFlow;Xamarin,PHPStorm;PyCharm,Linux-based,Development;Testing;Production,NaN,NaN,Yes,Yes,What?,Facebook,In real life (in person),Login,2013,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,31-60 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,A lot more welcome now than last year,Tech articles written by other developers;Tech...,NaN,Too long,Neither easy nor difficult
87231,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Nepal,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,2-9 employees,"Developer, back-end;Developer, full-stack;Student",8,14,2,Very satisfied,Slightly satisfied,I don't have a manager,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,Office environment or company culture;Remote w...,I heard about a job opportunity (from a recrui...,USD,United States dollar,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Lack of...,About half the time,Office,A little above average,"Yes, because I see value in code review",14.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have some influence,Assembly;Bash/Shell/PowerShell;C;C++;Dart;HTML...,Elixir;Erlang;TypeScript,Firebase;MariaDB;MySQL;SQLite,Cassandra;Couchbase;DynamoDB;Elasticsearch;Mon...,Android;Arduino;Linux;Raspberry Pi;Slack;Windo...,AWS;Docker;Heroku;Kubernetes,jQuery;Vue.js,Django;Express;Laravel;React.js;Vue.js,Flutter,Ansible;Apache Spark;Chef;Hadoop;Node.js;Puppet,Sublime Text;Visual Studio Code,Linux-based,Development;Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Yes,Yes,WhatsApp,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,Multiple times per day,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,25.0,Appropriate in length,Easy
87568,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Nepal,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Participated in a full-time developer training...,2-9 employees,"Academic researcher;Designer;Developer, back-e...",4,18,3,Neither satisfied nor dissatisfied,Slightly satisfied,Somewhat confident,No,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,Write any code;Complete a take-home project,No,Office environment or company culture;Remote w...,"My job status changed (promotion, new job, etc.)",NPR,Nepalese rupee,25000.0,Monthly,2640.0,44.0,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Lack of s...,"Less than half the time, but at least one day ...",Home,Average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,C;C++;C#;HTML/CSS;JavaScript;PHP;SQL;TypeScript,Java;JavaScript;PHP;TypeScript,Firebase;MariaDB;MongoDB;Microsoft SQL Server;...,Firebase;MongoDB;MySQL,Windows;WordPress,Android;AWS;Docker;iOS;Slack,ASP.NET;Express;jQuery;Laravel;React.js;Vue.js,Django;Express;Laravel;Vue.js,Apache Spark;.NET;Node.js,Flutter;Node.js;Puppet;Xamarin,IntelliJ;Notepad++;PHPStorm;Sublime Text;Visua...,Windows,Development;Testing;Production,Not at all,NaN,Yes,Also Yes,Yes,YouTube,Online,UserID,2015,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was slightly faster,60+ minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,23.0,Too long,Easy
88543,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Nepal,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Developer, full-stack;DevOps specialist",9,14,4,Slightly satisfied,Slightly dissatisfied,Somewhat confident,No,Yes,I am actively looking for a job,1-2 years ago,Complete a take-home project,Yes,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,NPR,Nepalese rupee,NaN,Monthly,NaN,NaN,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",8.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,HTML/CSS;JavaScript;PHP;Python;SQL,HTML/CSS;JavaScript;PHP;Python;TypeScript;WebA...,MongoDB;MySQL,Cassandra;Elasticsearch;MongoDB,Google Cloud Platform;Heroku;Kubernetes;Linux;...,AWS;Google Cloud Platform;Kubernetes;Linux;Win...,Angular/Angular.js;Express;jQuery;Laravel;Vue.js,Ruby on Rails,Cordova;Node.js;TensorFlow;Unity 3D,Hadoop;Torch/PyTorch;Unreal Engine,IPython / Jupyter;PHPStorm;PyCharm;Visual Stud...,Windows,Development;Testing;Production;Outside of work...,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,Yes,No,YouTube,In real life (in person),Username,2008,Less than once per month or monthly,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers,NaN,Too long,Easy

In [23]:
country_grp

In [29]:
country_grp['SocialMedia'].value_counts().head(50)

Country              SocialMedia
Afghanistan          Facebook                     15
                     YouTube                       9
                     I don't use social media      6
                     WhatsApp                      4
                     Instagram                     1
                     Twitter                       1
                     LinkedIn                      1
Albania              WhatsApp                     18
                     Facebook                     16
                     Instagram                    13
                     YouTube                      10
                     Twitter                       8
                     LinkedIn                      7
                     Reddit                        6
                     I don't use social media      4
                     WeChat 微信                     1
                     Snapchat                      1
Algeria              YouTube                      42
                     Facebook                     41
                     Twitter                      14
                     LinkedIn                      9
                     I don't use social media      7
                     Instagram                     7
                     WhatsApp                      2
                     Reddit                        2
Andorra              I don't use social media      2
                     Facebook                      2
                     Reddit                        1
                     YouTube                       1
                     Snapchat                      1
Angola               Twitter                       2
                     Facebook                      1
                     YouTube                       1
Antigua and Barbuda  YouTube                       2
                     Twitter                       1
                     Facebook                      1
                     Instagram                     1
                     VK ВКонта́кте                 1
Argentina            WhatsApp                    202
                     Twitter                      80
                     YouTube                      62
                     Instagram                    53
                     Reddit                       50
                     Facebook                     45
                     I don't use social media     22
                     LinkedIn                     16
Armenia              Facebook                     38
                     YouTube                      23
                     LinkedIn                      5
                     Reddit                        3
Name: count, dtype: int64

In [38]:
country_grp['SocialMedia'].value_counts(normalize=True).loc['United States']

SocialMedia
Reddit                      0.284346
Twitter                     0.173002
Facebook                    0.141874
YouTube                     0.122867
I don't use social media    0.092338
Instagram                   0.082410
LinkedIn                    0.050883
WhatsApp                    0.030380
Snapchat                    0.016263
WeChat 微信                   0.004639
VK ВКонта́кте               0.000449
Weibo 新浪微博                  0.000399
Hello                       0.000100
Youku Tudou 优酷              0.000050
Name: proportion, dtype: float64

In [42]:
country_grp['ConvertedComp'].median()

Country
Afghanistan                               6222.0
Albania                                  10818.0
Algeria                                   7878.0
Andorra                                 160931.0
Angola                                    7764.0
                                          ...
Venezuela, Bolivarian Republic of...      6384.0
Viet Nam                                 11892.0
Yemen                                    11940.0
Zambia                                    5040.0
Zimbabwe                                 19200.0
Name: ConvertedComp, Length: 179, dtype: float64

In [44]:
country_grp['ConvertedComp'].agg(['mean','median'])

                                               mean    median
Country
Afghanistan                           101953.333333    6222.0
Albania                                21833.700000   10818.0
Algeria                                34924.047619    7878.0
Andorra                               160931.000000  160931.0
Angola                                  7764.000000    7764.0
...                                             ...       ...
Venezuela, Bolivarian Republic of...   14581.627907    6384.0
Viet Nam                               17233.436782   11892.0
Yemen                                  16909.166667   11940.0
Zambia                                 10075.375000    5040.0
Zimbabwe                               34046.666667   19200.0

[179 rows x 2 columns]

In [49]:
filt=df['Country']=='India'
df[filt]['LanguageWorkedWith'].str.contains('Python').sum()

np.int64(3105)

In [56]:
country_grp['LanguageWorkedWith'].apply(lambda x: (x.str.contains('Python').sum()/x.count())*100).loc['United States']

/tmp/ipykernel_122449/1398644843.py:1: RuntimeWarning: invalid value encountered in scalar divide
  country_grp['LanguageWorkedWith'].apply(lambda x: (x.str.contains('Python').sum()/x.count())*100).loc['United States']

np.float64(48.54831720352448)

In [57]:
country_grp_respondents=df['Country'].value_counts()
country_grp_respondents

Country
United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Papua New Guinea                        1
Saint Kitts and Nevis                   1
Saint Vincent and the Grenadines        1
Sao Tome and Principe                   1
Chad                                    1
Name: count, Length: 179, dtype: int64

In [66]:
knowspython=country_grp['LanguageWorkedWith'].apply(lambda x: (x.str.contains('Python').sum()))

In [70]:
new_df=pd.concat([country_grp_respondents,knowspython,],sort=False,axis='columns')
new_df

                                  count  LanguageWorkedWith
Country
United States                     20949               10083
India                              9061                3105
Germany                            5866                2451
United Kingdom                     5737                2384
Canada                             3395                1558
...                                 ...                 ...
Papua New Guinea                      1                   0
Saint Kitts and Nevis                 1                   0
Saint Vincent and the Grenadines      1                   0
Sao Tome and Principe                 1                   1
Chad                                  1                   0

[179 rows x 2 columns]

In [74]:
new_df.rename(columns={'count':'Total-participants','LanguageWorkedWith':"KnowsPython"},inplace=True)
new_df

                                  Total-participants  KnowsPython
Country
United States                                  20949        10083
India                                           9061         3105
Germany                                         5866         2451
United Kingdom                                  5737         2384
Canada                                          3395         1558
...                                              ...          ...
Papua New Guinea                                   1            0
Saint Kitts and Nevis                              1            0
Saint Vincent and the Grenadines                   1            0
Sao Tome and Principe                              1            1
Chad                                               1            0

[179 rows x 2 columns]

In [75]:
new_df['Per%knows-python']=(new_df['KnowsPython']/new_df['Total-participants'])*100

In [76]:
new_df

,Total-participants,KnowsPython,Per%knows-python
Country,,,
United States,20949,10083,48.131176
India,9061,3105,34.267741
Germany,5866,2451,41.783157
United Kingdom,5737,2384,41.554820
Canada,3395,1558,45.891016
...,...,...,...
Papua New Guinea,1,0,0.000000
Saint Kitts and Nevis,1,0,0.000000
Saint Vincent and the Grenadines,1,0,0.000000
Sao Tome and Principe,1,1,100.000000
Chad,1,0,0.000000

In [81]:
new_df.sort_values(by="Per%knows-python",inplace=True,ascending=False)

In [83]:
new_df.head(30)

                           Total-participants  KnowsPython  Per%knows-python
Country
Sao Tome and Principe                       1            1        100.000000
Timor-Leste                                 1            1        100.000000
Niger                                       1            1        100.000000
Dominica                                    1            1        100.000000
Turkmenistan                                7            6         85.714286
Mauritania                                  7            5         71.428571
Guyana                                      3            2         66.666667
Guinea                                      3            2         66.666667
Bahamas                                     3            2         66.666667
Uganda                                     72           47         65.277778
Iceland                                    49           30         61.224490
Benin                                       5            3         60.000000
Haiti                                       5            3         60.000000
Namibia                                     5            3         60.000000
Congo, Republic of the...                   7            4         57.142857
Oman                                       11            6         54.545455
Cuba                                       30           16         53.333333
Republic of Korea                          39           20         51.282051
Monaco                                      4            2         50.000000
Seychelles                                  2            1         50.000000
Sierra Leone                                2            1         50.000000
San Marino                                  2            1         50.000000
South Korea                               160           80         50.000000
Bhutan                                      2            1         50.000000
Chile                                     206          102         49.514563
Finland                                   546          266         48.717949
Kenya                                     249          120         48.192771
United States                           20949        10083         48.131176
Israel                                    952          457         48.004202
Ecuador                                    82           39         47.560976